Admin_Login_Project/Admin_Login_App/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (
    admin_login_view, dashboard_view, logout_view, user_logout,admin_login_submit,
    AdminLoginAPI, get_admin_usernames,
    CourseListCreateView, CourseDetailView, CourseUpdateView, CourseDeleteView,
    course_view, course_page_view, navbar_save_view,navbar_view_course,
    update_course, delete_course, view_course, export_courses_csv, export_courses_excel, export_courses_pdf, 
    listing_api, KeywordListView,
    RegisterView, LogoutView
    # MyTokenObtainPairView, MyTokenRefreshView
)

urlpatterns = [

    # path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', MyTokenRefreshView.as_view(), name='token_refresh'),
    path('register/', RegisterView.as_view(), name='register'),

    path('admin_login/', admin_login_view, name='admin_login'),
    path('admin_login_submit/', admin_login_submit, name='admin_login_submit'),
    
    path('dashboard/', dashboard_view, name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user_logout/', user_logout, name='user_logout'),
    
    path('api/admin_login/', AdminLoginAPI.as_view(), name='admin_login_api'),
    path('api/get_admin_usernames/', get_admin_usernames.as_view(), name='get_admin_usernames'),
    
    path('api/courses/', CourseListCreateView.as_view(), name='course_list_create'),
    path('api/courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('api/update_courses/<int:pk>/', CourseUpdateView.as_view(), name='course_update'),
    path('api/delete_courses/<int:pk>/', CourseDetailView.as_view(), name='course_delete'),
    
    # path('courses/', course_view, name='courses'),
    # path('courses/', course_view, name='courses'),  # Main courses view
    # path('courses/<int:page>/', course_view, name='course-by-page'),  # Paginated view
    path('course_page/', course_page_view, name='course_page'),
    path('navbar_save_course/', navbar_save_view, name='navbar_save_course'),
    path('navbar_view_course/', navbar_view_course, name='navbar_view_course'),
    path('update_course/<int:id>/', update_course, name='update_course'),
    path('view_course/<int:id>/', view_course, name='view_course'),
    path('delete_course/<int:id>/', delete_course, name='delete_course'),
    
    # path('pdf/', pdf, name='pdf'),
    # path('excel/', excel_view, name='excel'),
    # path('csv/', csv_view, name='csv'),
    
    path('export_courses_csv/', export_courses_csv, name='export_courses_csv'),
    path('export_courses_excel/', export_courses_excel, name='export_courses_excel'),
    path('export_courses_pdf/', export_courses_pdf, name='export_courses_pdf'),
    
    path("course", KeywordListView.as_view(),name="course"),
    # path("course/<int:page>/", listing, name="course-page"),
    # path("page/", listing_api, name="course-api"),
    # path("page/<int:page>/", listing_api, name="course-api"),
    
    
    
    path('courses/', course_view, name='courses'),  # Main courses view
    path('page/', listing_api, name='course-api'),  # API endpoint for courses pagination
    path('page/<int:page>/', course_view, name='course-by-page'),  # Paginated view
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Admin_Login_Project/Admin_Login_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Admin_Login_App.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

Admin_Login_Project/Admin_Login_App/models.py
import datetime
import os
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor.fields import RichTextField

def getFileName(request, filename):
    return os.path.join('Images/', filename)

def getlogo(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time, filename)
    return os.path.join('logo/', new_filename)

def picture(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time, filename)
    return os.path.join('picture/', new_filename)

def video(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time, filename)
    return os.path.join('video/', new_filename)

def blog_images(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time, filename)
    return os.path.join('media/', new_filename)

class AdminLoginManager(BaseUserManager):
    def create_user(self, username, email, ph_no, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            ph_no=ph_no,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, ph_no, password=None):
        user = self.create_user(
            email=email,
            username=username,
            ph_no=ph_no,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class AdminLogin(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=150, unique=True)
    ph_no = PhoneNumberField(unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = AdminLoginManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'ph_no']

    def __str__(self):
        return self.username

class Course(models.Model):
    Title = models.CharField(max_length=100)
    Description = RichTextField()
    Technologies = models.CharField(max_length=150)
    Images = models.ImageField(upload_to=getFileName, blank=False)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.Title
    
class Technology(models.Model):
    Technologies = models.CharField(max_length=150)

class PartnerLogo(models.Model):
    name = models.CharField(max_length=100, default=None)
    logo = models.ImageField(upload_to=getlogo)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

class Testimonial(models.Model):
    student_name = models.CharField(max_length=100)
    picture = models.ImageField(upload_to=picture, blank=False)
    course = models.CharField(max_length=100)
    date = models.DateField()
    testimonial = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

class PlacementStory(models.Model):
    student_name = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    testimonial_video = models.FileField(upload_to=video, blank=False)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

class Blog(models.Model):
    images = models.ImageField(upload_to=blog_images, blank=False)
    title = models.CharField(max_length=100)
    description = models.TextField()
    course = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

class Career(models.Model):
    Logo = models.ImageField(upload_to=getlogo, blank=False)
    Job_Heading = models.CharField(max_length=100)
    Location = models.CharField(max_length=100)
    Experience = models.CharField(max_length=100)
    No_Of_Openings = models.CharField(max_length=100)
    Salary = models.FloatField()
    Status = models.BooleanField(default=True)
    Job_Type = models.CharField(max_length=100)
    Qualification = models.CharField(max_length=255)
    Job_Description = models.TextField()
    Skills_Required = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

Admin_Login_Project/Admin_Login_App/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *
from ckeditor.widgets import CKEditorWidget
from django.utils.safestring import mark_safe

# ----------------------------- Registration Form ----------------------------

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = AdminLogin
        fields = ('username', 'email', 'ph_no', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

# ----------------------------- Course Forms ----------------------------

class CoursesForm(forms.Form):
    Title = forms.CharField(label="Course Name", max_length=100)
    Description = forms.CharField(widget=CKEditorWidget())
    Technologies = forms.CharField(label="Topics", max_length=150)
    Images = forms.ImageField(label="Banner Images")
    status = forms.BooleanField(required=False)

class ImagePreviewWidget(forms.ClearableFileInput):
    def render(self, name, value, attrs=None, renderer=None):
        html = super().render(name, value, attrs, renderer)
        if value and hasattr(value, 'url'):
            image_html = f'<img id="{name}_image_preview" src="{value.url}" alt="Course Banner" style="max-width: 50px; max-height: 50px;">'
            script = f'<script>document.getElementById("{name}").addEventListener("change", function() {{ document.getElementById("{name}_image_preview").src = window.URL.createObjectURL(this.files[0]); }});</script>'
            return mark_safe(f'{image_html}<br>{html}{script}')
        return html

class UpdateCourseForm(forms.Form):
    Title = forms.CharField(label="Course Name", max_length=100)
    Description = forms.CharField(widget=CKEditorWidget())
    Technologies = forms.CharField(label="Topics", max_length=150)
    Images = forms.ImageField(label="Banner Images", widget=ImagePreviewWidget, required=False)
    status = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop('instance', None)
        super(UpdateCourseForm, self).__init__(*args, **kwargs)
        if instance:
            self.fields['Title'].initial = instance.Title
            self.fields['Description'].initial = instance.Description
            self.fields['Technologies'].initial = instance.Technologies
            self.fields['Images'].initial = instance.Images
            self.fields['status'].initial = instance.status


class viewCourseForm(forms.Form):
    Title = forms.CharField(label="Course Name", max_length=100)
    Description = forms.CharField(widget=CKEditorWidget())
    Technologies = forms.CharField(label="Topics", max_length=150)
    Images = forms.ImageField(label="Banner Images", widget=ImagePreviewWidget, required=False)

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop('instance', None)
        super(viewCourseForm, self).__init__(*args, **kwargs)
        if instance:
            self.fields['Title'].initial = instance.Title
            self.fields['Description'].initial = instance.Description
            self.fields['Technologies'].initial = instance.Technologies
            self.fields['Images'].initial = instance.Images
# ----------------------------- Partners Logo Form ----------------------------

class PartnersLogoForm(forms.ModelForm):
    class Meta:
        model = PartnerLogo
        fields = ['name', 'logo']

# ----------------------------- FAQ Form ----------------------------

class FaqForm(forms.ModelForm):
    class Meta:
        model = FAQ
        fields = ['question', 'answer']

Admin_Login_Project/templates/Admin_Login_App/AdminLogin.html
<html>
{% extends 'Admin_Login_App/base.html' %}

{% load static %}
{% load bootstrap_icons %}

{% block title %} Administration {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/AdminLogin1.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid admin-main-div">
    <div class="z-n1 position-absolute img-div">
        <img src="{% static 'images/wave1.svg' %}" alt="wave">
    </div>
    <div class="container">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-6 col-md-6 border left-div">
                    <img src="{% static 'images/logo-1.png' %}" class="img-fluid rounded-start mx-auto d-block mt-5" alt="Nschool Logo">
                    <div class="admin-div">
                        <img src="{% static 'images/Admin_image.webp' %}" class="admin-img" alt="Admin img">
                    </div>
                </div>
                <div class="col-6 col-md-6">
                    <div class="col-12 card-body">
                        <div class="admin-login-div">
                            <div class="input-div clearfix">
                                <form id="login-form" method="post" action="{% url 'admin_login_submit' %}" class="form-div">
                                    {% csrf_token %}
                                    <div>
                                        <p>Login as an admin user</p>
                                    </div>

                                    <div class="user-input-wrp">
                                        <input type="text" name="username" id="username" class="form-control" aria-label="Username" placeholder=" " autocomplete="off" autofocus>
                                        <label class="floating-label">Username</label>
                                    </div>

                                    <div class="text-danger span_div" id="user_error"></div>

                                    <div class="user-input-wrp">
                                        <input type="password" name="password" id="password" class="form-control" aria-label="Password" placeholder=" ">
                                        <label class="floating-label">Password</label>
                                    </div>

                                    <div class="text-danger span_div" id="pass_error"></div>

                                    <input type="submit" value="Login" class="btn login-btn">

                                    {% if error %}
                                    <div class="text-danger">{{ error }}</div>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("login-form").addEventListener("submit", function (event) {
            event.preventDefault(); // Prevent form submission

            var username = document.getElementById("username").value.trim();
            var password = document.getElementById("password").value.trim();

            if (username === "" && password === "") {
                document.getElementById("user_error").innerText = "Username is empty";
                document.getElementById("pass_error").innerText = "Password is empty";
                document.getElementById("username").focus();
                return;
            }

            document.getElementById("user_error").innerText = "";
            document.getElementById("pass_error").innerText = "";

            let hasError = false;
            if (username == "") {
                document.getElementById("user_error").innerText = "Username is empty";
                hasError = true;
            }
            if (password == "") {
                document.getElementById("pass_error").innerText = "Password is empty";
                hasError = true;
            }

            if (hasError) {
                return;
            }

            var data = {
                username: username,
                password: password,
            };

            // const jwtToken = localStorage.getItem('accessToken');

            // console.log(jwtToken)

            fetch("/api/admin_login/", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": document.querySelector('[name=csrfmiddlewaretoken]').value,
                    // "X-CSRFToken": document.querySelector('[name=csrfmiddlewaretoken]').value,
                    // "Authorization": `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4ODkzNzI3LCJpYXQiOjE3MTg4OTAxMjcsImp0aSI6ImFlMDQ5MzMyYjUxMjQ5YjI4YzI1YjgxMmNiM2Y3MmUyIiwidXNlcl9pZCI6MX0.7vJBpo6tMYmdtk24qY62GcJMpVh2dv4WcA8_hlxFzVE` 
                },
                body: JSON.stringify(data)
            })
            .then(response => {
                if (!response.ok) {
                    return response.json().then(err => {
                        throw new Error(err.detail || "Invalid username or password");
                    });
                }
                return response.json();
            })
            .then(data => {
                if (data) {
                    // localStorage.setItem('access', data.access);
                    // localStorage.setItem('refresh', data.refresh);
                    
                    // Fetch admin usernames
                    fetch("{% url 'get_admin_usernames' %}", {
                        method: 'GET',
                        headers: {
                            // 'Authorization': `Bearer ${data.access}`,
                            'Content-Type': 'application/json'
                        }
                    })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error("Failed to fetch admin usernames");
                        }
                        return response.json();
                    })
                    .then(adminUsernames => {
                        // Store admin usernames for validation
                        localStorage.setItem('adminUsernames', JSON.stringify(adminUsernames));
                        window.location.href = "{% url 'dashboard' %}";
                    })
                    .catch(error => {
                        console.error("Error:", error);
                        document.getElementById("pass_error").innerText = error.message || "An unexpected error occurred. Please try again later.";
                    });
                } else {
                    document.getElementById("pass_error").innerText = "Invalid credentials";
                }
            })
            .catch(error => {
                console.error("Error:", error);
                document.getElementById("pass_error").innerText = error.message || "An unexpected error occurred. Please try again later.";
            });
        });
    });
</script>
{% endblock %}
</html>

Admin_Login_Project/templates/Admin_Login_App/Admin_Body.html
{% extends 'Admin_Login_App/base.html' %}
{% load static %}
{% load bootstrap_icons %}

{% block title %} Dashboard {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
{% endblock %}

<!-- header -->
{% block header %}
    {% include 'Admin_Login_App/Admin_Header.html' %}
{% endblock %}


{% block content %}

<div class="container-fluid">
    <div class="row bg-body-tertiary">

        <!-- navbar -->

        {% block sidenavbar %}

        {% include 'Admin_Login_App/Side_Navbar.html' %}

        {% endblock %}

        <!-- dashboard -->

        {% block dashboard %}

        {% include 'Admin_Login_App/dashboard.html' %}
        
        {% endblock %}
    </div>
</div>

{% endblock %}

Admin_Login_Project/templates/Admin_Login_App/partners_logo_form.html
{% load static %}
{% load bootstrap_icons %}

{% block course_list %}
<div class="container" id="specific-div">
 
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="panel panel-default border">
                    <div class="panel-heading ps-3">
                        <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'pencil' %}  <span class="Add_Course">Add Logo</span></h3>
                    </div>
                    <div class="panel-body bg-white px-3 py-3">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Name</label>
                                <div>
                                    <input type="text" name="name" id="title" class="form-control" autocomplete="off">
                                </div>
                            </div>
                
                            <div class="form-group">
                                <label for="image">Logo</label>
                                <input type="file" name="logo" id="images" class="form-control-file">
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   
</div>
{% endblock %}

Admin_Login_Project/templates/Admin_Login_App/placement_stories.html
{% extends 'Admin_Login_App/base.html' %}
{% load static %}
{% load bootstrap_icons %}

<!-- title -->
{% block title %} Placement Stories {% endblock %}

<!-- Link css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/Admin_Header.css' %}">
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'css/side_navbar.css' %}">
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'css/course_page.css' %}">
<link rel="stylesheet" href="{% static 'css/course_list.css' %}">
{% endblock %}

<!-- link js -->
{% block link_js %}

{% endblock %}

<!-- header -->
{% block header %}
{% include 'Admin_Login_App/Admin_Header.html' %}
{% endblock %}

<!-- body content -->
{% block content %}

<div class="container-fluid">
    <div class="row bg-body-tertiary">

        <!-- side navbar -->

        {% block sidenavbar %}

        {% include 'Admin_Login_App/Side_Navbar.html' %}

        {% endblock %}

        <!-- navbar -->
        <div class="col-10 pb-5" style="background-color: #f6f6f6;">
            <div class="row">

                {% block stories_navbar %}

                <div id="navbar-content">

                    {% include 'Admin_Login_App/stories_navbar.html' %}

                </div>

                {% endblock %}


                {% block stories_list %}

                <div id="stories-content">
                    <!-- This is where the course content will be displayed -->

                    {% include 'Admin_Login_App/stories_list.html' %}

                </div>
                {% endblock %}


            </div>
        </div>

    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
    // v1
    // Function to check all checkboxes
    function checkAll() {
        var checkboxes = document.querySelectorAll('.check');
        var checkallCheckbox = document.getElementById('checkall');

        checkboxes.forEach(function (checkbox) {
            checkbox.checked = checkallCheckbox.checked;
        });
    }

    function loadStoriesPage() {
        // Specify the URL from which to fetch the new content
        const url = "{% url 'stories_form' %}";

        // Fetch content from the URL using the provided URL
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.text();
            })
            .then(html => {
                // Replace the HTML content of a specific div with the fetched data
                document.getElementById('stories-content').innerHTML = html;
            })
            .catch(error => console.error('Fetch error:', error));
    }

    function loadNavbarPage() {
        // Specify the URL from which to fetch the new content
        const url = "{% url 'navbar_save_course' %}";

        // Fetch content from the URL using the provided URL
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.text();
            })
            .then(html => {
                // Replace the HTML content of a specific div with the fetched data
                document.getElementById('navbar-content').innerHTML = html;
            })
            .catch(error => console.error('Fetch error:', error));      
    }
    
    function updateStoriesPage(url) {

        // Fetch content from the URL using the provided URL
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.text();
            })
            .then(html => {
                // Replace the HTML content of a specific div with the fetched data
                document.getElementById('stories-content').innerHTML = html;
            })
            .catch(error => console.error('Fetch error:', error));      
    }
</script>
{% endblock %}

Admin_Login_Project/templates/Admin_Login_App/testimonial_update.html
{% load static %}
{% load bootstrap_icons %}

{% block testimonial_list %}
<div class="container" id="specific-div">
 
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="panel panel-default border">
                    <div class="panel-heading ps-3">
                        <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'pencil' %}  <span class="Add_Course">Edit Testimonial</span></h3>
                    </div>
                    <div class="panel-body bg-white px-3 py-3">
                        <form method="POST" action="{% url 'update_testimonial' datas.id %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">student_name</label>
                                <div>
                                    <input type="text" name="student_name" id="title" value="{{ datas.student_name }}" class="form-control" autocomplete="off">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="id_description">testimonial</label>
                                <textarea id="id_description" name="testimonial" class="form-control"> {{datas.testimonial}} </textarea>
                            </div>
                            <div class="form-group">
                                <label for="technologies">course</label>
                                <input type="text" name="course" id="technologies" value="{{ datas.course }}" class="form-control" autocomplete="off">
                            </div>
                            <div class="form-group">
                                <label for="technologies">date</label>
                                <input type="date" name="date" id="technologies" value="{{ datas.date }}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="technologies">picture</label>
                                <img src="{{ datas.picture.url }}" alt="{{ datas.picture }}" style="max-height: 40px;">
                                <input type="file" name="picture" id="technologies" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary">update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   
</div>
{% endblock %}

Admin_Login_Project/templates/Admin_Login_App/view_course.html
{% load static %}
{% load bootstrap_icons %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/view_course.css' %}">
{% endblock %}

{% block course_list %}
<div class="container" id="specific-div" data-course-id="{{ datas.id }}">

    <div class="row">
        <div class="col-12 mx-auto">
            <div class="panel panel-default border">
                <div class="panel-heading ps-3">
                    <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'eye-fill' %} <span class="Add_Course">View
                            Courses</span></h3>
                </div>
                <div class="panel-body bg-white px-3 py-3">
                    <form id="data-form">
                        <!-- Form fields will be dynamically generated here -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}